server:
  port: 8080

webhook:
  token: "your_webhook_token_here"

github:
  tokens:
    # GitHub Personal Access Token - 可查询任意 GitHub 用户
    - token: "ghp_your_github_token_here"

llm:
  provider: "deepseek"
  api_key: "sk-your-api-key-here"
  model: "deepseek-chat"
  base_url: "https://api.deepseek.com/v1"

notifiers:
  feishu:
    enabled: true
    webhook_url: "https://open.feishu.cn/open-apis/bot/v2/hook/your-hook-here"
